# Use a base image with Java and a browser
FROM selenium/standalone-chrome:latest

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the test project files to the container
COPY . .

# Install Maven (if your project is Maven-based)
RUN apt-get update && \
    apt-get install -y maven

# Compile the project (Assuming it's a Maven project)
RUN mvn clean test-compile

# Command to run tests using the testng.xml file
CMD ["mvn", "test", "-Dsurefire.suiteXmlFiles=testng.xml"]
